default: &default
 adapter: "postgresql"
 host: containers-us-west-68.railway.app
 username: containers-us-west-68.railway.app
 password: fAjAmnitB1TJUK2WTvGJ
 port: 5879

development:
 <<: *default
 database: railway

test:
 <<: *default
 database: Project_Journal_test

production:
 <<: *default
 database: railway